name: CI


on:
  push:
    # Run for pushes to master or a version branch, e.g. a PR was merged ...
    branches:
      - android
      - ci_update
      - v[0-9]+.[0-9]+.[0-9]+
    # ... and only when we've possibly changed how the game will function.
    paths:
    - 'android/**'
    - 'source/**'
    - 'data/**'
    - 'tests/**'
    - '.github/workflows/**'
    - keys.txt
    - SConstruct
    - .winmake
    - .codespell.exclude
  pull_request:
    # Run for any push to any pull request, if it modifies source code or game text.
    types: [opened, synchronize]
    paths:
    - 'android/**'
    - 'source/**'
    - 'data/**'
    - 'tests/**'
    - 'EndlessSky.xcodeproj/**'
    - 'XCode/**'
    - '.github/workflows/**'
    - keys.txt
    - SConstruct
    - .winmake
    - .codespell.exclude


jobs:
  build_ubuntu:
    # TODO: only build if source changed. otherwise, d/l latest continuous
    runs-on: ubuntu-latest
    env:
        ANDROID_SDK_ROOT: /path/to/sdk 
        ARTIFACT: endless-mobile
    steps:
    - uses: actions/checkout@v2
    
    - name: Install development dependencies
      run: |
        sudo rm /etc/apt/sources.list.d/* && sudo dpkg --clear-avail # Speed up installation and get rid of unwanted lists
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libsdl2-dev libpng-dev libjpeg-turbo8-dev libopenal-dev libmad0-dev libglew-dev libgl1-mesa-dev uuid-dev ccache libgles2-mesa
        python3 -m pip install --user scons
    - name: Print toolchain versions
      run: |
        g++ -v
        gcc-ar --version
        ld -v
        scons --version
        python --version
    - name: Compile
      run: |
        scons -Qj $(nproc) opengl=gles mode=debug test;
#    - name: Upload game binary
#      uses: actions/upload-artifact@v2
#      with:
#        name: binary-${{ matrix.os }}-${{ matrix.opengl }}
#        path: ${{ env.ARTIFACT }}

  
